security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints
logging: # <----New sections below
  level:
    com: DEBUG
greeting:
  displayFortune: false # <----Change to true
